import {
  type Icon as LucideIcon,
  ArrowRight,
  Home,
  Info,
  Layers,
  MapPin,
  User,
  LoaderCircle,
  Bell,
  PieChart,
  UserRound,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ChevronDown,
  ChevronUp,
  ArrowDown,
  Trash2,
  ArrowUp,
  MoreVertical,
  FileCheck,
  Eye,
  EyeOff,
  LogOutIcon,
  Calendar,
  MoreHorizontal,
  Image,
  Plus,
  SquarePen,
  Search,
  ArrowLeft,
  PaintRoller,
  ShoppingCart,
  FolderSymlink,
  BriefcaseBusiness,
  FolderSearch,
  ContactRound,
  Boxes,
  Tags,
  Box,
  Package,
  BadgePercent,
  ClipboardList,
  Wallet,
  Landmark,
  SquarePlus,
  FileClock,
  Users,
  UserRoundCheck,
  Sliders,
  MapPinCheck,
  BellDot,
  FileChartPie,
  Settings2,
  LayoutDashboard,
  X,
  Minus,
  UserRoundPlus,
  Filter,
  Copy,
  Shapes,
  SlidersHorizontal,
  Calendar1,
} from "lucide-react";

export type Icon = typeof LucideIcon;

export type IconAdminPages = keyof typeof adminPages;
export type IconSettings = keyof typeof settings;
export type IconSocial = keyof typeof social;
export type IconUi = keyof typeof ui;
export type IconUiIndicator = keyof typeof uiIndicators;
export type Icons = keyof typeof Icons;

const settings = {
  help: CircleHelp,
  logout: LogOutIcon,
  bell: Bell,
};

const adminPages = {
  dashboard: LayoutDashboard,
  meeting: Calendar,
  bill: ShoppingCart,
  newBill: SquarePlus,
  creditBill: FileClock,
  MyBills: FolderSymlink,
  record: Calendar,
  events: FolderSearch,
  briefcase: BriefcaseBusiness,
  clients: ContactRound,
  warehouse: Boxes,
  categories: Tags,
  inventory: Box,
  contacts: Users,
  products: Package,
  discounts: BadgePercent,
  adjustmentHistory: ClipboardList,
  accountsReceivable: Wallet,
  paymentsReceived: Landmark,
  settings: Settings2,
  usersAndRoles: UserRoundCheck,
  generalSettings: Sliders,
  locations: MapPinCheck,
  notifications: BellDot,
  reports: FileChartPie,
  attributes: SlidersHorizontal,
};

const social = {};

const ui = {
  logo: PaintRoller,
  home: Home,
  img: Image,
  mapPin: MapPin,
  chartPie: PieChart,
  users: UserRound,
  service: Layers,
  user: User,
  userPlus: UserRoundPlus,
  copy: Copy,
  layers: Layers,
  shapes: Shapes,
  slidersHorizontal: SlidersHorizontal,
};

const uiIndicators = {
  info: Info,
  loader: LoaderCircle,
  trash: Trash2,
  close: X,
  edit: SquarePen,
  eye: Eye,
  eyeOff: EyeOff,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  fileCheck: FileCheck,
  plus: Plus,
  minus: Minus,
  search: Search,
  filter: Filter,
};

export const Icons = {
  ...ui,
  ...uiIndicators,
  ...social,
  ...adminPages,
  ...settings,
};
